apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: greeter
  namespace: test100
spec:
  template:
    metadata:
      annotations:
                            # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "10"      
    spec:
      containers:
      - image: quay.io/anandpavithran/infosys:1.0
