apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test1
  namespace: test100-serverless
spec:
  template:
    metadata:
      annotations:
        # Standard Kubernetes CPU-based autoscaling.
        autoscaling.knative.dev/class: hpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: cpu
    spec:
      containers:
        - image: quay.io/anandpavithran/infosys:1.0
