apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test2
  namespace: test100-serverless
spec:
  template:
    metadata:
      annotations:
        # Knative concurrency-based autoscaling (default).
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        # Target 10 requests in-flight per pod.In case of hpa its cpu %
        autoscaling.knative.dev/target: "10"
        # Disable scale to zero with a minScale of 1.
        autoscaling.knative.dev/minScale: "1"
        # Limit scaling to 100 pods.
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containers:
        - image: quay.io/anandpavithran/infosys:1.0
